// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkETKbcpJcX6EvfJKDsGCoFfpbZdAvUiE',
    appId: '1:1068176163188:web:dcadae6b65cc7858906c21',
    messagingSenderId: '1068176163188',
    projectId: 'mcclecture-12445',
    authDomain: 'mcclecture-12445.firebaseapp.com',
    storageBucket: 'mcclecture-12445.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYkfgUGSx5cWf3HPvgoU69X7IJAdtl9ew',
    appId: '1:1068176163188:android:9b9cedffe0a95c96906c21',
    messagingSenderId: '1068176163188',
    projectId: 'mcclecture-12445',
    storageBucket: 'mcclecture-12445.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4MSBcIMKxxK79u-EZ06Lr5-jbpWZq49o',
    appId: '1:1068176163188:ios:cbccad863d61e85d906c21',
    messagingSenderId: '1068176163188',
    projectId: 'mcclecture-12445',
    storageBucket: 'mcclecture-12445.appspot.com',
    iosClientId: '1068176163188-pto8f123ed7dg80bgh1ltunlcmephnnu.apps.googleusercontent.com',
    iosBundleId: 'com.example.feLecFinalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4MSBcIMKxxK79u-EZ06Lr5-jbpWZq49o',
    appId: '1:1068176163188:ios:cbccad863d61e85d906c21',
    messagingSenderId: '1068176163188',
    projectId: 'mcclecture-12445',
    storageBucket: 'mcclecture-12445.appspot.com',
    iosClientId: '1068176163188-pto8f123ed7dg80bgh1ltunlcmephnnu.apps.googleusercontent.com',
    iosBundleId: 'com.example.feLecFinalproject',
  );
}
